---
title: "Introduction"
page-layout: full
---

## History of the Climate Vulnerability Assessment

The Climate Vulnerability Assessment (CVA) was originally performed by the Northeast Fisheries Science Center in 2015. This original work, which was later replicated by all the National Marine Fisheries Service (NMFS) regions, used expert opinions to rank how target species would be impacted by future climate change using both exposure and sensitivity attributes. For the original CVA in the northeast US, experts ranked how much change species would be exposed to using large glocal ocean model forecasts and how sensitive they would be to these changes. This resulted in a single exposure and sensitivity score for each species, which was combined to give an overall vulnerability score. Experts were also asked to rank the directionality of climate impacts. The original methods are described in [Morrison et al 2015](https://www.st.nmfs.noaa.gov/Assets/ecosystems/climate/documents/TM%20OSF3.pdf) and [Hare et al 2016](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0146756), and the original results for the northeast shelf can be found in [Hare et al 2016](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0146756). CVA results for all regions can be explored using the [NOAA CVA Tool](https://www.fisheries.noaa.gov/data-tools/climate-vulnerability-assessment-tool).  

## Why CVA2.0?

The original CVA produced single metrics for each species across their entire range. However, in the past decade, it has become clear that climate change is not uniform worldwide. Therefore, species or stocks may be more or less vulnerable in different portions of their range. As a result, there is a need for a spatially explicit CVA. In addition, the development of high resolution regional ocean models such as the [MOM6 model](https://psl.noaa.gov/cefi_portal/) also allow changes to be predicted on fine spatial and temporal scales. The availability of the MOM6 hindcast and forecast on both decadal and long-term scales, plus new information on life history attributes for species, will allow us to update the existing CVA.  

## How to Use this Book

The purpose of this book is to document the methods and capture the decisions made in the development of the CVA2.0 for the Northeast Shelf, so that these methods could be broadly applied to other NMFS regions or management bodies. This book will also outline the R package that is actively in development to assist in reproducability across regions. Automatic reporting methods and any future RShiny application development to assist in gathering expert opinons will also be outlined here.  
