---
title: Acknowledgments
---

This project would not have been possible without the dedication and hardwork of countless individuals aboard the federal and state-run survey programs and the NOAA Observer program. 

Many thanks to the following programs for contributing data:

* [Northeast Fisheries Science Center (NEFSC) Bottom Trawl](https://www.fisheries.noaa.gov/about/northeast-ecosystems-surveys)
* [NEFSC Northern Shrimp Survey](https://www.fisheries.noaa.gov/inport/item/25087)
* [NEFSC Gulf of Maine Bottom Long Line Survey](https://www.fisheries.noaa.gov/new-england-mid-atlantic/science-data/gulf-maine-bottom-longline-survey)
* [NEFSC Atlantic Surfclam and Ocean Quahog Survey](https://www.fisheries.noaa.gov/inport/item/22565)
* [Northeast Area Monitoring and Assessment Program Nearshore Trawl](https://www.neamap.net/neamap-nearshore-trawl/)
* [Maine-New Hampshire Inshore Trawl Survey](https://www.neamap.net/menh-inshore-trawl/)
* [Massachusetts Division of Marine Fisheries Bottom Trawl Survey](https://www.neamap.net/madmf-bottom-trawl/)
* [Long Island Sound Trawl Survey](https://portal.ct.gov/deep/fishing/fisheries-management/long-island-sound-trawl-survey)
* [New York Nearshore Trawl Survey](https://www.neamap.net/ny-nearshore-trawl/)
* [New Jersey Ocean Stock Assessment Survey](https://dep.nj.gov/njfw/fishing/marine/ocean-stock-assessment-program/#:~:text=The%20New%20Jersey%20Ocean%20Stock,times%20throughout%20a%20calendar%20year.)
* [Delaware Trawl Surveys](https://dnrec.delaware.gov/fish-wildlife/fishing/research/)
* [National Observer Program](https://www.fisheries.noaa.gov/national/fisheries-observers/national-observer-program
* [Gillnet Observer Program](https://www.fisheries.noaa.gov/southeast/fisheries-observers/southeast-gillnet-observer-program)
* [Pelagic Observer Program](https://www.fisheries.noaa.gov/southeast/fisheries-observers/southeast-pelagic-observer-program)
* Southeast Fisheries Science Center Logbook Program 
* National Marine Fisheries Services' [Large Pelagics Survey](https://www.fisheries.noaa.gov/recreational-fishing-data/large-pelagics-survey-glance
)

Additional thanks to the Highly Migratory Species Group for providing additional tag data for smooth dogfish. 

We also thank all of the NOAA staff, members of the New England and Mid Atlantic Fisheries Management Councils, the Atlantic States Marine Fisheries Commission, and our academic partners for their feedback and assistance in developing the methods described here. 
