---
title: Species Exposure
---

Species exposure is quantified using the forecasts from the MOM6 model. The CVA2.0 follows similar methods to the original analysis while also integrating the species distribution model results. 

Exposure of each variable is calculated as a z-score using monthly averages across future (2025-2034) and present time periods (2014-2023). Global (not spatially or temporally explicit) averages and standard deviations were calculated from the present time series and used to calculate the z-score on monthly averaged future data to produce a spatially and temporally explicit exposure. 

Exposure values are then averaged across time and space each month to produce an exposure map and monthly timeseries for each variable, using predicted species distributions to perform weighted averages so that only expsoure within the species ranges are considered and habitat use by the species is taken into account. 

Total exposure is calculated using the same logic rule implimented in the CVA 1.0 in two different ways: 1) counting all ecologicaly relevant variables and 2) only counting variables that have relative weights over 10% in the species distribution models. This will be done across both time and space to produce both a total timeseries and map of exposure for each species. 
