---
title: Species Distribution Modeling
---

The first step in the CVA2.0 is the construction of species distribution models (SDMs). SDMs are statistical models that describe the relationships between species presence or abundance and environmental attributes or covariates. There are many different types of SDMs that use different data types and statistical methods. There is an abundance of scientific literature that both describe and compare different model types. We will provide a brief overview below and describe the methods selected for the CVA2.0.

## Presence/Absence vs Abundance Data

Species distribution models can be built with primarily two different kinds of species data - presence/absence or abundance data. Presence/absence data describes when a species was present or absent, usually in binary with 0s representing absences and 1s representing presences. SDMs built with presence/absence data predict how likely it is that a species will be found there - often called habitat suitability - but does not consider how many individuals will be present.

Abundance data on the other hand uses count or species density estimates. SDMS built with abundance data can predict the abundance or density of species in a given area or at a given time, but must deal with often irregular data.

#### In the CVA2.0...

For the CVA2.0, we use presence/absence data from a variety of sources. Using presence/absence data will allow us to combine multiple datasets across fisheries independent and dependent surveys.

## Statistical Modeling

There are many statistical models that we could have chosen for our SDMs. Options included generalized linear models (GLMs), generalized additive models (GAMs), uni (single) or multi-variate state-space models, machine learning methods, decision tree methods, and more! Many models have been used to describe species distributions along the Northeast Shelf. Each model type has pros and cons, and different models use different assumptions, statistical methods, etc to define habitat preferences.

To account for some of these differences between models, model ensembles can be generated by combining different model outputs together. Ensembles are usually built by averaging the outputs of different component models. Weighted averages can also be used to weight the averages based on model performance.

#### CVA2.0 Approach

We use an ensemble modeling approach for the CVA2.0, following the work of the Alaska Fisheries Science Center (AFSC)'s Groundfish program, recently implimented an [ensemble modeling framework](https://github.com/alaska-groundfish-efh/EFHSDM) for their [Essential Fish Habitat work](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2664.14559). Here, we use the following models to build our ensemble (henceforth referred to as **component models**):

1.  Generalized Additive Model (GAM) using methods in [EFHSDM](https://github.com/alaska-groundfish-efh/EFHSDM)
2.  MAXimum ENTropy (MAXENT) using methods in [EFHSDM](https://github.com/alaska-groundfish-efh/EFHSDM)
3.  [Random Forest with Spatial Interpolation (RFSI)](https://www.mdpi.com/2072-4292/12/10/1687)
4.  Boosted Regression Trees (BRTs) using [gbm](https://cran.r-project.org/web/packages/gbm/index.html) and following methods from [Braun et al 2023](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/eap.2893)
5.  Spatio-temporal Generalized Linear Mixed Models (GLMMs) with [sdmTMB](https://pbs-assess.github.io/sdmTMB/)

All of these models accept presence/absence data; can be made spatially and temporally explicit, which was important for our analysis; and combine more "traditional" SDM methods such as GAM and MAXENT included in the AFSC's ensemble with machine learning/decision tree-based models such as RFSI and BRTs. sdmTMB models are similar to other SDM methods common in fisheries work like [VAST](https://academic.oup.com/icesjms/article/74/5/1311/2907795#186891657) and [tinyVAST](https://arxiv.org/pdf/2401.10193). These models use spatial and temporal random fields to account for spatial and random variation in species distributions that the environmental variables cannot describe. In addition, these or similar models have been used on the Northeast Shelf in previously published works.

We will generate our ensemble model by performing a weighted average on our components' outputs. Weights will be calculated using the same methods as the AFSC. However, we will use Area under the Curve (AUC) rather than root mean squared error (RMSE) because AUC is a better accuracy metric for presence/absence models than RMSE. AUC will be scaled from 0-1, rather than its native 0.5 - 1 range, using the Gini Index to help better illustrate the spread of component model performance.
